### ISSUE TITLE
malformed muzzles

### ISSUE THREAD

**Issue by jonathon-love** [roma-lukashik/animal-avatar-generator#5]
hi,

i'm using 1.0.4 which ostensibly has the fix for #2 in it ... but the fix isn't there.

this is what's in my node_modules directory (see line 25 in muzzles.js):

<img width="1478" alt="Screen Shot 2022-02-18 at 12 38 33" src="https://user-images.githubusercontent.com/3240247/154601125-9bb46739-6c82-4917-bfc0-380a0f35399e.png">

cheers

**Comment by roma-lukashik** [comment]
Hi, 
thank you for reporting the issue. 

I've re-published the package, should be fixed in 1.0.5 version.

**Comment by jonathon-love** [comment]
pefect. i can confirm the issue is fixed in the 1.0.5.

thanks for such a fun and quirky package.

jonathon
