### ISSUE TITLE
Use css style for the svg size property

### ISSUE THREAD

**Issue by ngandon** [roma-lukashik/animal-avatar-generator#9]
I needed to be able to easily match the svg size to my parent element height

So I made a Pull request to solve this : https://github.com/roma-lukashik/animal-avatar-generator/pull/8

please feel free to merge if that's ok for you

**Comment by roma-lukashik** [comment]
Hi @ngandon,

thanks for the provided merge request.

Merged https://github.com/roma-lukashik/animal-avatar-generator/pull/8
